# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Smart Vendor' do
    pod 'SCLAlertView'
    pod 'Parse'
    pod 'Firebase', '>= 2.5.0'
end

target 'Smart VendorTests' do

end

target 'Smart VendorUITests' do

end

